### ISSUE TITLE
Deleting a file in the media library breaks a single document's download

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Document-Plugin#8]
**Describe the bug**

Deleting a file in the media library that's assigned to a document results in the document attempting to return a broken file for download. (rc-v0.1.0)

**Steps to Reproduce**

1. Create a new document post, upload a file in the "Uploaded File" field, and save
2. Delete the newly-uploaded file from the media library directly. Do not edit the document post
3. Navigate to the document
4. You should be prompted to download a broken/empty file

**Expected Behavior**

In this scenario, the single document URL should return a 404.

**Possible Fix**

Consider adding a filter on attachment delete that wipes the corresponding ACF field's value.

**Your environment:**

(all)

**Additional context**

n/a

**Comment by jmbarne3** [comment]
Fixed by #7
